version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anime_tracker_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MongoDB_URI=mongodb://mongodb:27017/anime_tracker
    depends_on:
      - mongodb
    networks:
      - anime_tracker_network

  mongodb:
    image: mongo:7.0
    container_name: anime_tracker_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - anime_tracker_network

volumes:
  mongodb_data:


networks:
  anime_tracker_network:
    driver: bridge
